import { Config, Data } from "@/core";
import { ButtonProps } from "./blocks/Button";
import { CardProps } from "./blocks/Card";
import { GridProps } from "./blocks/Grid";
import { HeroProps } from "./blocks/Hero";
import { HeadingProps } from "./blocks/Heading";
import { FlexProps } from "./blocks/Flex";
import { LogosProps } from "./blocks/Logos";
import { StatsProps } from "./blocks/Stats";
import { TemplateProps } from "./blocks/Template";
import { TextProps } from "./blocks/Text";
import { SpaceProps } from "./blocks/Space";
import type { GroupProps } from "./blocks/Group";
import type { ProductsGridProps } from "./blocks/ProductsGrid";
import type { ProductImageCarouselProps } from "./blocks/ProductImageCarousel";
import type { ProductVariantsProps } from "./blocks/ProductVariants";
import { CartSectionProps } from "./blocks/CartSection";
import type { CartListProps } from "./blocks/CartList";
import type { CartQuantityProps } from "./blocks/CartQuantity";
import { CheckoutFormProps } from "./blocks/CheckoutForm";
import { ProductSearchMenuProps } from "./blocks/ProductSearchMenu";
import { CategoryListMenuProps } from "./blocks/CategoryListMenu";
import { ProductImageProps } from "./blocks/ProductImage";
import { ProductInfoProps } from "./blocks/ProductInfo";
import { SectionProps } from "./blocks/Section";
import type { RowGroupProps } from "./blocks/RowGroup/types";

import { RootProps } from "./root";
import { RichTextProps } from "./blocks/RichText";
import { ContentHeadingProps } from "./blocks/ContentHeading";
import { ContentParagraphProps } from "./blocks/ContentParagraph";
import { AccordionProps } from "./blocks/Accordion";
import { ContentImageProps } from "./blocks/ContentImage";
import { ContentButtonProps } from "./blocks/ContentButton";
import { ButtonGroupProps } from "./blocks/ButtonGroup";
import { ContentLinkProps } from "./blocks/ContentLink";
import { ContentInputProps } from "./blocks/ContentInput";
import { ContentDividerProps } from "./blocks/ContentDivider";
import { ImageGalleryProps } from "./blocks/ImageGallery";
import { VideoEmbedProps } from "./blocks/VideoEmbed";
import { ContentIconProps } from "./blocks/ContentIcon";
import { ContentHtmlProps } from "./blocks/ContentHtml";
import { OrderHistoryProps } from "./blocks/OrderHistory";
import { WishlistProps } from "./blocks/Wishlist";
import { TestimonialsProps } from "./blocks/Testimonials";
import { ContactFormProps } from "./blocks/ContactForm";
import { SidebarProps } from "./blocks/Sidebar";
import { NavMenuProps } from "./blocks/NavMenu";
import { SideDrawerProps } from "./blocks/SideDrawer";
import { SiteHeaderProps } from "./blocks/SiteHeader";
import { SiteDrawerShellProps } from "./blocks/SiteDrawerShell";
import { SiteFooterProps } from "./blocks/SiteFooter";
import { ZoneDrawerProps } from "./blocks/ZoneDrawer";
import { ZonePopupProps } from "./blocks/ZonePopup";
import { ZoneBottomSheetProps } from "./blocks/ZoneBottomSheet";
import type { CartIconButtonProps } from "./blocks/CartIconButton";

export type { RootProps } from "./root";

export type Components = {
  SiteHeader: SiteHeaderProps;
  SiteDrawerShell: SiteDrawerShellProps;
  SiteFooter: SiteFooterProps;
  ZoneDrawer: ZoneDrawerProps;
  ZonePopup: ZonePopupProps;
  ZoneBottomSheet: ZoneBottomSheetProps;
  Section: SectionProps;
  Group: GroupProps;
  RowGroup: RowGroupProps;
  Button: ButtonProps;
  Card: CardProps;
  Grid: GridProps;
  Hero: HeroProps;
  Heading: HeadingProps;
  Flex: FlexProps;
  Logos: LogosProps;
  Stats: StatsProps;
  Template: TemplateProps;
  Text: TextProps;
  Space: SpaceProps;
  RichText: RichTextProps;
  ProductCard: GroupProps;
  ProductsGrid: ProductsGridProps;
  ProductImageCarousel: ProductImageCarouselProps;
  ProductVariants: ProductVariantsProps;
  CartSection: CartSectionProps;
  CartList: CartListProps;
  CartItem: GroupProps;
  CartQuantity: CartQuantityProps;
  CartIconButton: CartIconButtonProps;
  CheckoutForm: CheckoutFormProps;
  ProductSearchMenu: ProductSearchMenuProps;
  CategoryListMenu: CategoryListMenuProps;
  ProductImage: ProductImageProps;
  ProductInfo: ProductInfoProps;
  ContentHeading: ContentHeadingProps;
  ContentParagraph: ContentParagraphProps;
  Accordion: AccordionProps;
  ContentImage: ContentImageProps;
  ContentButton: ContentButtonProps;
  ButtonGroup: ButtonGroupProps;
  ContentLink: ContentLinkProps;
  ContentInput: ContentInputProps;
  ContentDivider: ContentDividerProps;
  ImageGallery: ImageGalleryProps;
  VideoEmbed: VideoEmbedProps;
  ContentIcon: ContentIconProps;
  ContentHtml: ContentHtmlProps;
  OrderHistory: OrderHistoryProps;
  Wishlist: WishlistProps;
  Testimonials: TestimonialsProps;
  ContactForm: ContactFormProps;
  Sidebar: SidebarProps;
  NavMenu: NavMenuProps;
  SideDrawer: SideDrawerProps;
};

export type UserConfig = Config<{
  components: Components;
  root: RootProps;
  categories: ["layout", "blocks", "storeBlocks", "legacy"];
  fields: {
    userField: {
      type: "userField";
      option: boolean;
    };
  };
}>;

export type UserData = Data<Components, RootProps>;
