import React, { useMemo } from "react";
import { ComponentConfig, Slot } from "@/core/types";
import type { ComponentDataOptionalId, SlotComponent } from "@/core/types";
import { getClassNameFactory } from "@/core/lib";
import { useAppStore } from "@/core/store";
import { resolveColor } from "../../content/color-fields";
import { createThemeColorField } from "../../fields/ThemeColorField";
import { createSpacingField } from "../../fields/SpacingField";
import { createColumnsField } from "../../fields/ColumnsField";
import { createOverlayField } from "../../fields/OverlayField";
import { WithLayout, withLayout } from "../../components/Layout";
import { ZONE_BLOCK_TYPES } from "../../shell-zones";
import { isMobileEditorMetadata } from "../../lib/editor-mode";
import { sectionCollectionPickerField } from "../../fields/CollectionPickerField";
import type { CollectionPickerRef } from "@/modules/product/collection/data-store";
import {
  DEFAULT_SECTION_NAME,
  createSectionStarterContent,
} from "./starter-data";
import {
  ensureProductsGridTemplate,
  isProductsGridSection,
  productsGridContentNeedsResync,
  SECTION_KIND_PRODUCTS_GRID,
  type SectionPresetMetadata,
} from "./products-grid-section";
import {
  ensureProductsPageTemplate,
  isProductsPageSection,
  productsPageContentNeedsResync,
  SECTION_KIND_PRODUCTS_PAGE,
} from "./products-page-section";
import { ProductsGridTemplateRepeater } from "./ProductsGridTemplateRepeater";
import { ProductsPageTemplateRepeater } from "./ProductsPageTemplateRepeater";
import { CustomerAddressesTemplateRepeater } from "./CustomerAddressesTemplateRepeater";
import {
  isCustomerAccountSection,
  isCustomerAddressesSection,
  SECTION_KIND_CUSTOMER_ACCOUNT,
  SECTION_KIND_CUSTOMER_ADDRESSES,
} from "./customer-account-section";
import {
  isCartSection,
  resolveCartSectionContent,
  SECTION_KIND_CART,
} from "./cart-section";
import {
  isZoneHeaderSection,
  SECTION_KIND_ZONE_HEADER,
  ZONE_SHELL_SECTION_PERMISSIONS,
} from "./zone-section";
import { CartSectionStorefront } from "./CartSectionStorefront";
import {
  getViewportBucket,
  normalizeBreakpoints,
  parseViewportWidthForBucket,
  readMobileBreakpointPx,
  type BreakpointThemeProps,
} from "../../theme";
import { BoundDataProvider } from "../../binding/BoundDataContext";
import { useSampleDataInEditor } from "../../data-adapter";
import { useStore } from "../../store-context";
import styles from "./styles.module.css";

const getClassName = getClassNameFactory("Section", styles);

function clampColumns(raw: unknown): number {
  return Math.max(1, Math.min(6, Number(raw ?? 1) || 1));
}

/** Active grid column count for the editor canvas viewport (mobile → columnsMobile). */
function useEditorActiveColumns(
  isEditing: boolean,
  columns: number,
  columnsMobile: number
): number {
  const viewportW = useAppStore((s) => s.state.ui.viewports.current.width);
  const rootBp = useAppStore(
    (s) => s.state.data.root.props as Partial<BreakpointThemeProps> | undefined
  );

  if (!isEditing) return columns;

  const bp = normalizeBreakpoints({
    breakpointMobileMax: rootBp?.breakpointMobileMax,
    breakpointTabletMax: rootBp?.breakpointTabletMax,
  });
  const bucket = getViewportBucket(parseViewportWidthForBucket(viewportW), bp);
  return bucket === "mobile" ? columnsMobile : columns;
}

// ─── Preset colours ────────────────────────────────────────────────────────
export const backgroundOptions = [
  { label: "White", value: "#ffffff" },
  { label: "Off-white", value: "#f8f9fa" },
  { label: "Light grey", value: "#f0f2f5" },
  { label: "Neutral grey", value: "#e5e7eb" },
  { label: "Soft blue", value: "#eff6ff" },
  { label: "Soft green", value: "#f0fdf4" },
  { label: "Soft yellow", value: "#fefce8" },
  { label: "Dark navy", value: "#0f172a" },
  { label: "Dark grey", value: "#1f2937" },
  { label: "Black", value: "#000000" },
  { label: "Transparent", value: "transparent" },
];

const maxWidthOptions = [
  { label: "كامل العرض", value: "100%" },
  { label: "عريض (1536px)", value: "1536px" },
  { label: "قياسي (1280px)", value: "1280px" },
  { label: "متوسط (1024px)", value: "1024px" },
  { label: "ضيق (768px)", value: "768px" },
];

// ─── Types ─────────────────────────────────────────────────────────────────

export type SectionProps = WithLayout<{
  /**
   * Human-readable name shown in the left-sidebar outline. Empty = fall back
   * to the default "Section" label. AI agents can set this to summarise a
   * section's role ("Hero", "Featured Products") so the merchant outline is
   * self-describing without inspecting children.
   */
  name?: string;
  /**
   * CSS id applied to the `<section>`. Pair this with a `LinkValue` of kind
   * "anchor" to build in-page nav — a `NavMenu` item with
   * `{ kind: "anchor", hash: "promo" }` scrolls to the Section whose
   * `anchorId === "promo"`. Kept separate from the Puck `id` (which is an
   * internal stable key generated by the reducer).
   */
  anchorId?: string;
  /**
   * When false the section is hidden in the published renderer (web + mobile).
   * In the editor it stays visible but dimmed so merchants can still edit it.
   * This flag is persisted in `store_config.json` under the section's props —
   * AI agents can flip it programmatically to A/B-test sections without
   * mutating the section's inner content.
   */
  visible?: boolean;
  paddingTop: string;
  paddingBottom: string;
  paddingHorizontal: string;
  backgroundColor: string;
  /** Controls inherited text/heading colour inside dark sections */
  theme: "dark" | "light";
  maxWidth: string;
  /** CSS grid column count for the content slot */
  columns?: number | string;
  /** Column count on viewports at or below 768px (default: 1) */
  columnsMobile?: number | string;
  /** Gap between grid cells */
  gridGap?: string;
  /** Background image URL (cover, centered) */
  backgroundImage?: string;
  /** Color overlay on top of background image (supports rgba for transparency) */
  backgroundOverlayColor?: string;
  /** @deprecated Prefer `metadata.preset`. Kept for older saved configs. */
  sectionKind?:
    | typeof SECTION_KIND_PRODUCTS_GRID
    | typeof SECTION_KIND_PRODUCTS_PAGE
    | typeof SECTION_KIND_CART
    | typeof SECTION_KIND_CUSTOMER_ACCOUNT
    | typeof SECTION_KIND_CUSTOMER_ADDRESSES
    | null;
  /** Identifies preset-driven sections (e.g. products-grid) in store_config.json. */
  metadata?: SectionPresetMetadata | null;
  /** Selected collection — available on every section; drives products-grid fill. */
  collection?: CollectionPickerRef | null;
  /** Raw slot snapshot for cart preset storefront rendering. */
  cartSlotItems?: ComponentDataOptionalId[] | null;
  /**
   * Raw snapshot of the products-grid card template (a single-item wrapper
   * around content[0]).
   *
   * Slots are exposed to render as a `Slot` component, not as the raw JSON
   * array, so the products-grid repeater needs this snapshot to clone the
   * template into non-editable cells 1..N. Kept in sync by resolveData
   * whenever the slot changes.
   *
   * NOTE: shaped as an array (not a single object) so Puck's field walker
   * treats it as a plain non-field array and returns it as-is — walking
   * into the object would mis-detect its inner `content` array as another
   * slot (the section's `content` field name shadows).
   */
  cardTemplate?: ComponentDataOptionalId[] | null;
  content: Slot;
}>;

// ─── Component config ──────────────────────────────────────────────────────

const SectionInner: ComponentConfig<SectionProps> = {
  label: "قسم",

  fields: {
    // ── Identity ─────────────────────────────────────────────────────────
    name: {
      type: "text",
      label: "اسم القسم (يظهر في المخطط)",
      placeholder: "e.g. Hero, Featured products",
      metadata: {
        helpText:
          "A friendly name helps you find this section quickly in the left outline.",
        example: "Featured products",
      },
    },
    anchorId: {
      type: "text",
      label: "معرف الرابط (للروابط الداخلية)",
      placeholder: "e.g. promo (no spaces)",
    },
    // ── Visibility ───────────────────────────────────────────────────────
    visible: {
      type: "radio",
      label: "الرؤية",
      metadata: {
        helpText:
          "Hide a section when you want to keep working on it without publishing it.",
      },
      options: [
        { label: "ظاهر", value: true },
        { label: "مخفي", value: false },
      ],
    },

    // ── Spacing (التخطيط tab — named levels from the theme scale) ────────
    paddingTop: createSpacingField({ label: "المسافة من الأعلى", axis: "vertical" }),
    paddingBottom: createSpacingField({ label: "المسافة من الأسفل", axis: "vertical" }),
    paddingHorizontal: createSpacingField({ label: "المسافة من الجانبين", axis: "side" }),

    // ── Background (الخلفية tab) ─────────────────────────────────────────
    backgroundColor: createThemeColorField({
      label: "لون الخلفية",
      context: "background",
      allowTransparent: true,
    }),
    backgroundImage: {
      type: "text",
      label: "صورة الخلفية (رابط)",
      placeholder: "https://example.com/image.jpg",
      metadata: {
        group: "background",
        helpText:
          "Optional background image URL. Shown as cover behind section content.",
      },
    },
    backgroundOverlayColor: createOverlayField({
      label: "التغطية فوق الصورة",
    }),
    theme: {
      type: "radio",
      label: "لون النص",
      metadata: { group: "typography" },
      options: [
        { label: "داكن", value: "dark" },
        { label: "فاتح (أبيض)", value: "light" },
      ],
    },

    // ── Container (التخطيط tab) ──────────────────────────────────────────
    maxWidth: {
      type: "select",
      label: "عرض المحتوى",
      options: maxWidthOptions,
    },

    columns: createColumnsField({ label: "أعمدة المحتوى" }),
    // columnsMobile deliberately has no field — the stored value still
    // renders, and gets its own control in the mobile builder instance.
    gridGap: createSpacingField({ label: "فجوة الشبكة", axis: "side" }),

    // ── Content slot ─────────────────────────────────────────────────────
    content: {
      type: "slot",
      disallow: ["Section", ...ZONE_BLOCK_TYPES],
    },
  },

  defaultProps: {
    name: DEFAULT_SECTION_NAME,
    anchorId: "",
    visible: true,
    paddingTop: "80px",
    paddingBottom: "80px",
    paddingHorizontal: "24px",
    backgroundColor: "#ffffff",
    theme: "dark",
    maxWidth: "1280px",
    columns: 1,
    columnsMobile: 1,
    gridGap: "24px",
    backgroundImage: "",
    backgroundOverlayColor: "",
    collection: null,
    content: createSectionStarterContent(),
  },

  resolveFields: (data, params) => {
    let fields = params.fields;

    if (isProductsGridSection(data.props)) {
      fields = {
        collection: sectionCollectionPickerField,
        ...fields,
      } as typeof fields;
    }

    if (isProductsPageSection(data.props)) {
      const { collection: _collection, ...rest } = fields as Record<
        string,
        unknown
      >;
      fields = rest as typeof fields;
    }

    if (isMobileEditorMetadata(params.metadata)) {
      fields = {
        ...fields,
        columnsMobile: createColumnsField({ label: "أعمدة الجوال" }),
      } as typeof fields;
    }

    return fields;
  },

  resolveData: async ({ props }, { changed, trigger }) => {
    if (isCartSection(props)) {
      const shouldSync =
        trigger === "insert" ||
        trigger === "force" ||
        trigger === "load" ||
        Boolean(changed.content);

      if (!shouldSync) return {};

      const resolved = resolveCartSectionContent(
        props.content as ComponentDataOptionalId[] | undefined
      );
      return {
        props: {
          content: resolved.content,
          cartSlotItems: resolved.cartSlotItems,
          columns: resolved.columns,
        },
      };
    }

    if (!isProductsGridSection(props) && !isProductsPageSection(props)) {
      return {};
    }

    const rawContent = props.content;
    const needsResync = isProductsGridSection(props)
      ? productsGridContentNeedsResync(rawContent)
      : productsPageContentNeedsResync(rawContent);
    const collectionChanged =
      isProductsGridSection(props) && Boolean(changed.collection);
    const contentChanged = Boolean(changed.content);
    const shouldNormalizeTemplate =
      needsResync ||
      trigger === "insert" ||
      trigger === "force" ||
      trigger === "load";

    const patch: Record<string, unknown> = {};
    const normalizedContent = shouldNormalizeTemplate
      ? isProductsGridSection(props)
        ? ensureProductsGridTemplate(rawContent)
        : ensureProductsPageTemplate(rawContent)
      : (rawContent as ComponentDataOptionalId[] | undefined);

    if (shouldNormalizeTemplate) {
      patch.content = normalizedContent;
    }

    if (
      shouldNormalizeTemplate ||
      contentChanged ||
      props.cardTemplate == null
    ) {
      patch.cardTemplate =
        normalizedContent && normalizedContent.length > 0
          ? [normalizedContent[0]]
          : [];
    }

    if (
      collectionChanged &&
      isProductsGridSection(props) &&
      props.collection?.name
    ) {
      patch.name = props.collection.name;
    }

    return Object.keys(patch).length > 0 ? { props: patch } : {};
  },

  resolvePermissions: (data, { permissions }) => {
    if (!isZoneHeaderSection(data.props)) {
      return permissions;
    }

    return {
      ...permissions,
      ...ZONE_SHELL_SECTION_PERMISSIONS,
    };
  },

  render: (props) => <SectionView {...props} />,
};

type SectionViewProps = SectionProps & {
  id?: string;
  puck: { isEditing?: boolean };
};

function SectionView({
  id,
  name: _name,
  anchorId,
  visible,
  paddingTop,
  paddingBottom,
  paddingHorizontal,
  backgroundColor,
  backgroundImage,
  backgroundOverlayColor,
  theme,
  maxWidth,
  columns,
  columnsMobile,
  gridGap,
  sectionKind,
  collection,
  metadata: sectionMetadata,
  cartSlotItems,
  cardTemplate,
  content: Content,
  puck,
}: SectionViewProps) {
  const cols = clampColumns(columns);
  // Default mobile layout: single column unless the merchant overrides.
  const colsMobile = clampColumns(columnsMobile ?? 1);
  const isEditing = puck.isEditing === true;
  const activeCols = useEditorActiveColumns(isEditing, cols, colsMobile);
  const { customer } = useStore();
  const sampleMode = isEditing && useSampleDataInEditor();

  const isProductsGrid = isProductsGridSection({
    sectionKind,
    metadata: sectionMetadata,
  });

  const isProductsPage = isProductsPageSection({
    sectionKind,
    metadata: sectionMetadata,
  });

  const isCustomerAccount = isCustomerAccountSection({
    sectionKind,
    metadata: sectionMetadata,
  });

  const isCustomerAddresses = isCustomerAddressesSection({
    sectionKind,
    metadata: sectionMetadata,
  });

  const customerAccountBoundData = useMemo(() => {
    if (sampleMode) {
      return {
        profile: {
          customerId: "sample-customer",
          fullName: "أحمد محمد",
          phone: "+963991234567",
          totalSpendSyp: 125000,
          orderCount: 7,
          lastOrderAt: "2026-01-15T10:00:00Z",
          createdAt: "2025-06-01T08:00:00Z",
        },
        preferences: {
          emailOptIn: true,
          smsOptIn: false,
          emailConsentedAt: "2025-06-01T08:00:00Z",
          smsConsentedAt: null,
        },
      };
    }
    return {
      profile: customer.profile,
      preferences: customer.preferences,
    };
  }, [sampleMode, customer.profile, customer.preferences]);

  const customerAccountProviderValue = useMemo(
    () => ({
      data: customerAccountBoundData,
      isLoading: false,
      isError: false,
      metadata: null,
      language: "ar" as const,
      selectedVariantId: null,
      setSelectedVariantId: () => {},
    }),
    [customerAccountBoundData]
  );

  const gap = gridGap ?? "24px";
  const bgImage = (backgroundImage ?? "").trim();
  const overlayColor = (backgroundOverlayColor ?? "").trim();
  const gridClassName = getClassName("grid");
  const sectionScopeId = id
    ? `section-${id.replace(/[^a-zA-Z0-9_-]/g, "-")}`
    : undefined;

  // Backward-compat: sections saved before the `visible` prop existed
  // (i.e. `visible === undefined`) default to visible.
  const isHidden = visible === false;

  // Published renderer (web + mobile) strips hidden sections entirely.
  // The editor keeps them interactive but visually demotes them so
  // merchants can still select and re-enable them from the fields panel.
  if (isHidden && !isEditing) {
    return <></>;
  }

  // Sanitise the anchor id — CSS ids cannot contain spaces. We trim and
  // replace whitespace so merchants don't have to learn the rules.
  const cleanAnchor = (anchorId ?? "").trim().replace(/\s+/g, "-");

  const gridStyle = {
    display: "grid",
    gridTemplateColumns: `repeat(${activeCols}, minmax(0, 1fr))`,
    gap,
    alignContent: "start",
    width: "100%",
  } as const;

  const productsGridRender = isProductsGrid ? (
    <ProductsGridTemplateRepeater
      // Puck types `content: Slot` on props but transforms it into a
      // SlotComponent at render — the widely-used `<Content />` pattern
      // relies on the same runtime coercion.
      editableSlot={Content as unknown as SlotComponent}
      cardTemplate={cardTemplate?.[0] ?? undefined}
      sectionId={id}
      collection={collection ?? null}
      isEditing={isEditing}
      activeCols={activeCols}
      gap={gap}
      gridClassName={gridClassName}
    />
  ) : null;

  const productsPageRender = isProductsPage ? (
    <ProductsPageTemplateRepeater
      editableSlot={Content as unknown as SlotComponent}
      cardTemplate={cardTemplate?.[0] ?? undefined}
      sectionId={id}
      isEditing={isEditing}
      activeCols={activeCols}
      gap={gap}
      gridClassName={gridClassName}
    />
  ) : null;

  const customerAddressesRender = isCustomerAddresses ? (
    <CustomerAddressesTemplateRepeater
      editableSlot={Content as unknown as SlotComponent}
      cardTemplate={cardTemplate?.[0] ?? undefined}
      sectionId={id}
      isEditing={isEditing}
      activeCols={activeCols}
      gap={gap}
      gridClassName={gridClassName}
    />
  ) : null;

  const defaultSectionContent = (
    <Content className={gridClassName} style={gridStyle} />
  );

  const customerAccountContent = isCustomerAccount ? (
    <BoundDataProvider value={customerAccountProviderValue}>
      {defaultSectionContent}
    </BoundDataProvider>
  ) : (
    defaultSectionContent
  );

  const sectionGridContent = isProductsGrid ? (
    productsGridRender
  ) : isProductsPage ? (
    productsPageRender
  ) : isCustomerAddresses ? (
    customerAddressesRender
  ) : (
    customerAccountContent
  );

  const wrappedSectionGridContent = sectionGridContent;

  return (
    <section
      id={cleanAnchor || sectionScopeId}
      data-section-id={sectionScopeId}
      data-section-preset={
        isProductsGridSection({ sectionKind, metadata: sectionMetadata })
          ? SECTION_KIND_PRODUCTS_GRID
          : isProductsPageSection({ sectionKind, metadata: sectionMetadata })
            ? SECTION_KIND_PRODUCTS_PAGE
          : isCartSection({ sectionKind, metadata: sectionMetadata })
            ? SECTION_KIND_CART
            : isCustomerAccountSection({ sectionKind, metadata: sectionMetadata })
              ? SECTION_KIND_CUSTOMER_ACCOUNT
              : isCustomerAddressesSection({ sectionKind, metadata: sectionMetadata })
                ? SECTION_KIND_CUSTOMER_ADDRESSES
                : isZoneHeaderSection({ sectionKind, metadata: sectionMetadata })
                  ? SECTION_KIND_ZONE_HEADER
                  : undefined
      }
      className={getClassName({ hidden: isHidden })}
      style={{
        paddingTop,
        paddingBottom,
        backgroundColor: bgImage ? undefined : backgroundColor,
        backgroundImage: bgImage ? `url(${bgImage})` : undefined,
        backgroundSize: bgImage ? "cover" : undefined,
        backgroundPosition: bgImage ? "center" : undefined,
        backgroundRepeat: bgImage ? "no-repeat" : undefined,
        color: theme === "light" ? "#ffffff" : "inherit",
        opacity: isHidden ? 0.35 : undefined,
        position: "relative",
      }}
    >
      {bgImage && overlayColor && (
        <div
          aria-hidden
          style={{
            position: "absolute",
            inset: 0,
            backgroundColor: resolveColor(overlayColor),
            pointerEvents: "none",
            zIndex: 0,
          }}
        />
      )}
      {sectionScopeId && colsMobile !== cols && (
        <style>{`
          @media (max-width: ${readMobileBreakpointPx()}px) {
            [data-section-id="${sectionScopeId}"] .${gridClassName} {
              grid-template-columns: repeat(${colsMobile}, minmax(0, 1fr)) !important;
            }
          }
        `}</style>
      )}
      {isHidden && isEditing && (
        <div
          aria-hidden
          style={{
            position: "absolute",
            top: 8,
            insetInlineStart: 8,
            padding: "2px 8px",
            background: "#111827",
            color: "#ffffff",
            fontSize: 11,
            fontWeight: 600,
            letterSpacing: "0.04em",
            textTransform: "uppercase",
            borderRadius: 4,
            zIndex: 1,
            pointerEvents: "none",
          }}
        >
          Hidden
        </div>
      )}
      <div
        className={getClassName("inner")}
        style={{
          maxWidth,
          paddingLeft: paddingHorizontal,
          paddingRight: paddingHorizontal,
          width: "100%",
          position: "relative",
          zIndex: 1,
        }}
      >
        {isCartSection({ sectionKind, metadata: sectionMetadata }) &&
        !isEditing ? (
          <CartSectionStorefront
            cartSlotItems={
              (cartSlotItems as ComponentDataOptionalId[] | null) ?? []
            }
            gridClassName={gridClassName}
            gridStyle={{
              display: "grid",
              gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))`,
              gap,
              alignContent: "start",
              width: "100%",
            }}
          />
        ) : (
          wrappedSectionGridContent
        )}
      </div>
    </section>
  );
}

export const Section = withLayout(SectionInner);
