import React from "react";
import { ComponentConfig, Slot } from "@/core/types";
import { getClassNameFactory } from "@/core/lib";
import { spacingOptions } from "../../options";
import { resolveColor } from "../../content/color-fields";
import { WithLayout, withLayout } from "../../components/Layout";
import {
  DEFAULT_SECTION_NAME,
  createSectionStarterContent,
} from "./starter-data";
import styles from "./styles.module.css";

const getClassName = getClassNameFactory("Section", styles);

// ─── Preset colours ────────────────────────────────────────────────────────
export const backgroundOptions = [
  { label: "White", value: "#ffffff" },
  { label: "Off-white", value: "#f8f9fa" },
  { label: "Light grey", value: "#f0f2f5" },
  { label: "Neutral grey", value: "#e5e7eb" },
  { label: "Soft blue", value: "#eff6ff" },
  { label: "Soft green", value: "#f0fdf4" },
  { label: "Soft yellow", value: "#fefce8" },
  { label: "Dark navy", value: "#0f172a" },
  { label: "Dark grey", value: "#1f2937" },
  { label: "Black", value: "#000000" },
  { label: "Transparent", value: "transparent" },
];

const maxWidthOptions = [
  { label: "Full width", value: "100%" },
  { label: "Wide (1536px)", value: "1536px" },
  { label: "Standard (1280px)", value: "1280px" },
  { label: "Medium (1024px)", value: "1024px" },
  { label: "Narrow (768px)", value: "768px" },
];

const columnOptions = [1, 2, 3, 4, 5, 6].map((n) => ({
  label: n === 1 ? "1 (full width)" : String(n),
  value: String(n),
}));

// ─── Types ─────────────────────────────────────────────────────────────────

export type SectionProps = WithLayout<{
  /**
   * Human-readable name shown in the left-sidebar outline. Empty = fall back
   * to the default "Section" label. AI agents can set this to summarise a
   * section's role ("Hero", "Featured Products") so the merchant outline is
   * self-describing without inspecting children.
   */
  name?: string;
  /**
   * CSS id applied to the `<section>`. Pair this with a `LinkValue` of kind
   * "anchor" to build in-page nav — a `NavMenu` item with
   * `{ kind: "anchor", hash: "promo" }` scrolls to the Section whose
   * `anchorId === "promo"`. Kept separate from the Puck `id` (which is an
   * internal stable key generated by the reducer).
   */
  anchorId?: string;
  /**
   * When false the section is hidden in the published renderer (web + mobile).
   * In the editor it stays visible but dimmed so merchants can still edit it.
   * This flag is persisted in `store_config.json` under the section's props —
   * AI agents can flip it programmatically to A/B-test sections without
   * mutating the section's inner content.
   */
  visible?: boolean;
  paddingTop: string;
  paddingBottom: string;
  paddingHorizontal: string;
  backgroundColor: string;
  /** Controls inherited text/heading colour inside dark sections */
  theme: "dark" | "light";
  maxWidth: string;
  /** CSS grid column count for the content slot */
  columns?: number | string;
  /** Column count on viewports at or below 768px (default: 1) */
  columnsMobile?: number | string;
  /** Gap between grid cells */
  gridGap?: string;
  /** Background image URL (cover, centered) */
  backgroundImage?: string;
  /** Color overlay on top of background image (supports rgba for transparency) */
  backgroundOverlayColor?: string;
  content: Slot;
}>;

// ─── Component config ──────────────────────────────────────────────────────

const SectionInner: ComponentConfig<SectionProps> = {
  label: "قسم",

  fields: {
    // ── Identity ─────────────────────────────────────────────────────────
    name: {
      type: "text",
      label: "اسم القسم (يظهر في المخطط)",
      placeholder: "e.g. Hero, Featured products",
      metadata: {
        helpText:
          "A friendly name helps you find this section quickly in the left outline.",
        example: "Featured products",
      },
    },
    anchorId: {
      type: "text",
      label: "معرف الرابط (للروابط الداخلية)",
      placeholder: "e.g. promo (no spaces)",
    },
    // ── Visibility ───────────────────────────────────────────────────────
    visible: {
      type: "radio",
      label: "الرؤية",
      metadata: {
        helpText:
          "Hide a section when you want to keep working on it without publishing it.",
      },
      options: [
        { label: "Visible", value: true },
        { label: "Hidden", value: false },
      ],
    },

    // ── Spacing ──────────────────────────────────────────────────────────
    paddingTop: {
      type: "select",
      label: "مسافة من الأعلى",
      metadata: {
        helpText: "Controls the breathing room at the top of this section.",
      },
      options: [{ label: "0px", value: "0px" }, ...spacingOptions],
    },
    paddingBottom: {
      type: "select",
      label: "مسافة من الأسفل",
      metadata: {
        helpText: "Controls the breathing room below this section.",
      },
      options: [{ label: "0px", value: "0px" }, ...spacingOptions],
    },
    paddingHorizontal: {
      type: "select",
      label: "مسافة جانبية",
      metadata: {
        helpText: "Adds room on the left and right, useful on mobile screens.",
      },
      options: [{ label: "0px", value: "0px" }, ...spacingOptions],
    },

    // ── Appearance ───────────────────────────────────────────────────────
    backgroundColor: {
      type: "select",
      label: "لون الخلفية",
      options: backgroundOptions,
    },
    backgroundImage: {
      type: "text",
      label: "صورة الخلفية (رابط)",
      placeholder: "https://example.com/image.jpg",
      metadata: {
        helpText:
          "Optional background image URL. Shown as cover behind section content.",
      },
    },
    backgroundOverlayColor: {
      type: "text",
      label: "لون التغطية فوق الصورة",
      placeholder: "rgba(0, 0, 0, 0.45)",
      metadata: {
        helpText:
          "Semi-transparent color over the background image. Use rgba for transparency.",
        example: "rgba(0, 0, 0, 0.45)",
      },
    },
    theme: {
      type: "radio",
      label: "لون النص",
      options: [
        { label: "Dark", value: "dark" },
        { label: "Light (white)", value: "light" },
      ],
    },

    // ── Container ────────────────────────────────────────────────────────
    maxWidth: {
      type: "select",
      label: "العرض الأقصى",
      options: maxWidthOptions,
    },

    columns: {
      type: "select",
      label: "أعمدة الشبكة",
      metadata: {
        helpText: "Split section content into simple columns.",
      },
      options: columnOptions,
    },
    columnsMobile: {
      type: "select",
      label: "أعمدة الشبكة (جوال)",
      metadata: {
        helpText: "Column count on screens 768px wide or smaller.",
      },
      options: columnOptions,
    },
    gridGap: {
      type: "select",
      label: "فجوة الشبكة",
      options: [{ label: "0px", value: "0px" }, ...spacingOptions],
    },

    // ── Content slot ─────────────────────────────────────────────────────
    content: {
      type: "slot",
      disallow: ["Section"], // no nested sections
    },
  },

  defaultProps: {
    name: DEFAULT_SECTION_NAME,
    anchorId: "",
    visible: true,
    paddingTop: "80px",
    paddingBottom: "80px",
    paddingHorizontal: "24px",
    backgroundColor: "#ffffff",
    theme: "dark",
    maxWidth: "1280px",
    columns: 1,
    columnsMobile: 1,
    gridGap: "24px",
    backgroundImage: "",
    backgroundOverlayColor: "",
    content: createSectionStarterContent(),
  },

  render: ({
    id,
    name: _name,
    anchorId,
    visible,
    paddingTop,
    paddingBottom,
    paddingHorizontal,
    backgroundColor,
    backgroundImage,
    backgroundOverlayColor,
    theme,
    maxWidth,
    columns,
    columnsMobile,
    gridGap,
    content: Content,
    puck,
  }) => {
    const cols = Math.max(1, Math.min(6, Number(columns ?? 1) || 1));
    const colsMobile = Math.max(
      1,
      Math.min(6, Number(columnsMobile ?? 1) || 1)
    );
    const gap = gridGap ?? "24px";
    const bgImage = (backgroundImage ?? "").trim();
    const overlayColor = (backgroundOverlayColor ?? "").trim();
    const gridClassName = getClassName("grid");
    const sectionScopeId = id ? `section-${id.replace(/[^a-zA-Z0-9_-]/g, "-")}` : undefined;

    // Backward-compat: sections saved before the `visible` prop existed
    // (i.e. `visible === undefined`) default to visible.
    const isHidden = visible === false;

    // Published renderer (web + mobile) strips hidden sections entirely.
    // The editor keeps them interactive but visually demotes them so
    // merchants can still select and re-enable them from the fields panel.
    if (isHidden && !puck.isEditing) {
      return <></>;
    }

    // Sanitise the anchor id — CSS ids cannot contain spaces. We trim and
    // replace whitespace so merchants don't have to learn the rules.
    const cleanAnchor = (anchorId ?? "").trim().replace(/\s+/g, "-");

    return (
      <section
        id={cleanAnchor || sectionScopeId}
        data-section-id={sectionScopeId}
        className={getClassName({ hidden: isHidden })}
        style={{
          paddingTop,
          paddingBottom,
          backgroundColor: bgImage ? undefined : backgroundColor,
          backgroundImage: bgImage ? `url(${bgImage})` : undefined,
          backgroundSize: bgImage ? "cover" : undefined,
          backgroundPosition: bgImage ? "center" : undefined,
          backgroundRepeat: bgImage ? "no-repeat" : undefined,
          color: theme === "light" ? "#ffffff" : "inherit",
          opacity: isHidden ? 0.35 : undefined,
          position: "relative",
        }}
      >
        {bgImage && overlayColor && (
          <div
            aria-hidden
            style={{
              position: "absolute",
              inset: 0,
              backgroundColor: resolveColor(overlayColor),
              pointerEvents: "none",
              zIndex: 0,
            }}
          />
        )}
        {sectionScopeId && colsMobile !== cols && (
          <style>{`
            @media (max-width: 768px) {
              [data-section-id="${sectionScopeId}"] .${gridClassName} {
                grid-template-columns: repeat(${colsMobile}, minmax(0, 1fr)) !important;
              }
            }
          `}</style>
        )}
        {isHidden && puck.isEditing && (
          <div
            aria-hidden
            style={{
              position: "absolute",
              top: 8,
              insetInlineStart: 8,
              padding: "2px 8px",
              background: "#111827",
              color: "#ffffff",
              fontSize: 11,
              fontWeight: 600,
              letterSpacing: "0.04em",
              textTransform: "uppercase",
              borderRadius: 4,
              zIndex: 1,
              pointerEvents: "none",
            }}
          >
            Hidden
          </div>
        )}
        <div
          className={getClassName("inner")}
          style={{
            maxWidth,
            paddingLeft: paddingHorizontal,
            paddingRight: paddingHorizontal,
            width: "100%",
            position: "relative",
            zIndex: 1,
          }}
        >
          <Content
            className={gridClassName}
            style={{
              display: "grid",
              gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))`,
              gap,
              alignContent: "start",
              width: "100%",
            }}
          />
        </div>
      </section>
    );
  },
};

export const Section = withLayout(SectionInner);
